### ISSUE TITLE
user.cfg has certain paths hardcoded

### ISSUE THREAD

**Issue by luzpaz** [dulouie/FreeCAD-modern-config#3]
* https://github.com/dulouie/FreeCAD-modern-config/blob/master/user.cfg#L11  
* https://github.com/dulouie/FreeCAD-modern-config/blob/master/user.cfg#L29  
* https://github.com/dulouie/FreeCAD-modern-config/blob/master/user.cfg#L336 (assumes the user uses Blender Navigation)
* https://github.com/dulouie/FreeCAD-modern-config/blob/master/user.cfg#L475 (assumes user installed via the PPA)  
* https://github.com/dulouie/FreeCAD-modern-config/blob/master/user.cfg#L477-L482 (shows recent files that don't exist on users system)  
* There are other assumptions the users system has like addons and workbenches and Macros.

**Comment by luzpaz** [comment]
bump

**Comment by dulouie** [comment]
Refactoring is in progress. And thanks for your help :)
